import "./globals.css";
import Header from "@/components/Header";
import ContextProvider from "@/context/context";

export const metadata = {
  title: "2016 政治獻金資訊平台",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <Header />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
